<?= $this->extend('Dashboard/dashboard') ?>

<?= $this->section('content') ?>

<div class="bg-[#eaeaea] py-5 h-full">
    <h1 class="text-center py-[3rem] font-bold text-3xl">History Page</h1>
<p class="px-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti similique maxime fugiat minima ipsa voluptatum, doloribus aliquam maiores vitae adipisci nemo blanditiis deserunt veniam, sint dolorum eos nobis deleniti distinctio? Consectetur necessitatibus harum libero ratione doloremque ex sint, rem earum ipsa, ad exercitationem, enim reiciendis. Cumque quos quaerat voluptatum tempore perferendis laboriosam alias, provident repellendus cupiditate necessitatibus ea in exercitationem qui maiores atque sed facere quas pariatur architecto. Quis fugiat sapiente voluptate eum, deserunt voluptatibus ratione? Eius, est ullam sed perspiciatis tempora neque ipsam aut, quod nulla non obcaecati eum sint possimus dignissimos commodi sapiente repellat totam qui necessitatibus iusto! Blanditiis, quaerat deserunt. Neque ipsam tempore adipisci atque totam nulla perspiciatis sed impedit beatae dolorum ex autem alias quod assumenda laboriosam nam, doloremque harum quasi quis inventore rem a! Corporis aspernatur atque labore consequuntur sint velit placeat commodi iure neque, nostrum officia animi quidem maxime perferendis molestias reprehenderit eos, adipisci quam, facere vitae. Illum, culpa. Distinctio tempore veniam accusantium? Amet animi molestias optio dignissimos quaerat quidem ad alias, repellendus quis commodi temporibus vel aspernatur ipsa minima consequatur, adipisci dolor sit libero laborum voluptatem reiciendis! Ab provident illum qui nam soluta vitae, expedita neque ex. Quibusdam iure delectus laboriosam necessitatibus dolor nulla tempore repellat quasi porro soluta eligendi molestiae quidem doloribus odit, ipsa hic voluptate consequatur! Optio, voluptas? Pariatur eos delectus, obcaecati porro error quasi libero distinctio quidem dolores. Aliquid iusto laudantium deserunt laborum facilis ipsam. Veniam dolorem architecto harum commodi velit mollitia. Recusandae impedit eveniet tempora perferendis quis rem, voluptatibus corrupti nesciunt est, itaque minus ducimus voluptates ut quos deleniti aspernatur quidem? Hic consequatur, sunt nesciunt maiores nostrum minus quia voluptatibus et nisi expedita libero suscipit voluptas laboriosam velit fugiat vitae repudiandae nihil. Natus praesentium qui laborum, odit reiciendis voluptatem repellat laudantium, vitae eius necessitatibus, nulla perferendis vero. Illo, voluptate.</p>
</div>

<?= $this->endSection() ?>